 _format_version: "2.1"
 _transform: true

 services:
   - name: expense-service
     url: http://host.docker.internal:9820
     routes:
       - name: expense-route
         paths:
          - /expense/v1
         strip_path: false
         preserve_host: false
     plugins:
       - name: custom-auth
         config:
           auth_service_url: "http://host.docker.internal:9898/auth/v1/ping"

   - name: auth-service
     url: http://host.docker.internal:9898
     routes:
       - name: auth-route
         paths:
           - /auth/v1
         strip_path: false
         preserve_host: false
